### ISSUE TITLE
Incompatibility with nuxt-vuex-localstorage

### ISSUE THREAD

**Issue by DooDesch** [gabrielmbmb/vuex-multi-tab-state#17]
First of, this is an awesome plugin and works like charm on it's own!
I'm using it for a social login in a seperate tab and sync it to the previous tab which is working as expected.

**My problem :**
When using it with https://github.com/rubystarashe/nuxt-vuex-localstorage this plugin, that syncs localstorage to vuex and will update if the version is changed, your plugin will always overwrite all changes, so I'm not able to update the content that I'm storing in the vuex file, if it's not stored already.

**My workaround atm :** 
Checking if there's a difference in the content and if, clear everything and reset it.
Using the other plugin on it's own, it would just be changing the version number.

**Comment by gabrielmbmb** [comment]
Hey, thank you for reporting the issue. Could you give me a more extensive explanation? If you show me some code snippets it could help a lot!

**Comment by gabrielmbmb** [comment]
Hey @DooDesch, I just published v1.0.14 which fix some bugs with objects. Can you try to update and check if your problem has been fixed?

**Comment by kfsz** [comment]
I think the problem is that, on page load it automatically forces state from local storage into main state.  

For example you have store with `{'color': 'red', 'amount': 'lots' }`. You open the page and state gets saved into local storage. Then you edit store to now contain `{'color': 'red', 'amount': 9, type: 'apple' }`. You open the page and amount is still `'lots'` (and string), while type is `undefined` as both values were loaded from what was in state. You now have to clear data from local storage and reload to have proper defaults/types in state.  

nuxt-vuex-localstorage seems to deal with that by keeping additional value in store (`version` by default), and when that value is changed it knows not to load (and to remove) old data from local storage (as the store was changed and that data is no longer valid).
