### ISSUE TITLE
How to set settings in nuxt

### ISSUE THREAD

**Issue by jonalxh** [gabrielmbmb/vuex-multi-tab-state#29]
Hi, I'm currently working in a Nuxt project and I want your plugin to just store the login data, I've tried the follogin with not success:

```
// plugins/multiTabState.client.js

import createMultiTabState from 'vuex-multi-tab-state';

export default ({ store }) => {
  createMultiTabState({
      statesPaths: [
        'userLogged',
        'userDetails',
      ]
  })(store);
};
```

Without setting it works as expected, storing all my state variables, but setting some paths it just stop working, my store is the following:

```
// store/session.js
export const state = () => ({
   userLogged: false,
   userDetails: {},
   // A lot of variables
})
```

I'm using the multiple state variables to logout on all browser tabs when session expires, but I want the other data to keep locally instead of globally.

I hope you can help me.

**Comment by gabrielmbmb** [comment]
I suppose you have added the plugin in the `nuxt.config.js`, right?

**Comment by jonalxh** [comment]
Yes, it is added, as I told before it works without settings.

**Comment by gabrielmbmb** [comment]
I'll have to review this problem further. I hope to be able to give you a solution soon.

**Comment by gabrielmbmb** [comment]
Hi again @jonalxh. I think that your problem is that you want to sync the variables `userLogged` and `userDetails` from the module `sessions.js`, therefore you should write the following:

```js
// plugins/multiTabState.client.js

import createMultiTabState from 'vuex-multi-tab-state';

export default ({ store }) => {
  createMultiTabState({
      statesPaths: [
        'session.userLogged',
        'session.userDetails',
      ]
  })(store);
};
```

 I've updated the nuxt example and add a store module called `animals.js` that will only sync the variable `wolf`. You can check the example here: [nuxt vuex-multi-tab-state example](https://github.com/gabrielmbmb/vuex-multi-tab-state/tree/master/examples/nuxt). Try what I told you and if the problem persist, tell me!

**Comment by jonalxh** [comment]
Hi @gabrielmbmb, thanks a lot, It worked.
